### PR TITLE
Fix 'vagrant ssh -c "make postflight"'

### PR DESCRIPTION
**Pull request by nickbp**
```
cannot enable tty mode on non tty input
make: *** [postflight] Error 1
```

### CODE REVIEW

**Comment by karlkfi** [comment]
This patch will make postflight only work when executed in a shell with a tty. I'm not sure we want to do that. The usually trick is to detect a tty with a shell test and optionally print the `-t`, btu I'm not sure how to do it in make. In bash it's like `$([ -t 1 ] && echo '-t')`.

**Comment by jessfraz** [comment]
You can do it in make like this
https://github.com/docker/docker/blob/master/Makefile#L71

**Comment by karlkfi** [comment]
You're a make wizard, @jessfraz !
You wanna patch that in, @nickbp ?

**Comment by tamarrow** [comment]
Closing, since this is fixed by #27

**Pull request closed without merging**
