### PR TITLE
[DCOS-15644] Remove systemd commands from Makefile

### PR DESCRIPTION
**Pull request by adamtheturtle**
## High Level Description

This removes the dependency on systemd on the host.

## Related Issues
  - [DCOS-15644](https://jira.mesosphere.com/browse/DCOS-15644) Remove systemd host commands from DC/OS Docker

## Notes

My understanding is that previously, useless systemd configuration files were created with the following content:

```
[Unit]
Description=Mesos Executors Slice
```

I am not a systemd expert but it seems that `systemctl start`ing this would have no impact. Therefore I have removed this.

This should also remove `systemd` from the requirements in the README but that is done in a follow-up which rearranges things.

## Testing

Running `make` and then `make postflight` in the Vagrant environment succeeds with this branch.

Running `make` on macOS fails with a non-systemd error, showing that the process at least gets further on platforms without systemd.

### CODE REVIEW

**Comment by adamtheturtle** [comment]
cc @mhrabovcin @tillt @karlkfi

**Comment by karlkfi** [comment]
Have you verified this on Linux?

**Comment by adamtheturtle** [comment]
@karlkfi Yes, as per the PR description, I have run `make` and `make postflight` in the Vagrant VM and these showed that the cluster created is healthy. Is there other testing that you would like me to do?

**Comment by adamtheturtle** [comment]
Closing while I investigate something

**Comment by karlkfi** [comment]
So I'm pretty sure the reason the slice was initially added by @jessfraz was to allow managing the resources of the dcos-docker containers as a group.
https://www.freedesktop.org/software/systemd/man/systemd.slice.html

This would allow you to constraint the cpu/mem without requiring the use of a VM.

Is there any way we can make this slice optional instead of removing it completely?

**Comment by adamtheturtle** [comment]
@karlkfi Ah, I didn't get that and I still don't understand how it works here really.

Would you prefer:
* Run these commands if `systemctl` is available
* By default, don't run these commands, but provide an overridable variable which allows these commands to be run

?

**Comment by mhrabovcin** [comment]
This looks like the target is no-op by default. Maybe we can prefix the `systemctl` calls with `-` so the errors are ignored? Another option would be to run these commands only if the unit slice was defined as a variable or overridden in a command line.

**Comment by adamtheturtle** [comment]
Unfortunately this is not a no-op. It just turns out that `make postflight` isn't as comprehensive a check as I thought it was. This does not affect master nodes, but agent nodes don't start properly. `dcos-mesos-slave` and `docs-metrics-agent` fail.

The following is particularly damning:

```
[root@dcos-docker-agent1 /]# journalctl -f -u dcos-mesos-slave
-- Logs begin at Fri 2017-05-12 00:54:04 UTC. --
May 12 01:20:26 dcos-docker-agent1 mesos-agent[14668]: I0512 01:20:26.015447 14675 agent.cpp:264] Configuring overlay network 'dcos'
May 12 01:20:26 dcos-docker-agent1 mesos-agent[14668]: I0512 01:20:26.063282 14676 agent.cpp:758] Docker network 'dcos' already exists
May 12 01:20:26 dcos-docker-agent1 mesos-agent[14668]: I0512 01:20:26.063547 14676 agent.cpp:603] Insert following iptables rule for overlay dcos: ipset add -exist overlay
9.0.0.0/8 nomatch && iptables -t nat -C POSTROUTING -s 9.0.0.0/8 -m set --match-set overlay dst -j MASQUERADE || iptables -t nat -A POSTROUTING -s 9.0.0.0/8 -m set --match-
set overlay dst -j MASQUERADE
May 12 01:20:26 dcos-docker-agent1 mesos-agent[14668]: I0512 01:20:26.080912 14668 systemd.cpp:238] systemd version `219` detected
May 12 01:20:26 dcos-docker-agent1 mesos-agent[14668]: I0512 01:20:26.081563 14668 main.cpp:342] Inializing systemd state
May 12 01:20:26 dcos-docker-agent1 mesos-agent[14668]: I0512 01:20:26.090184 14668 systemd.cpp:326] Started systemd slice `mesos_executors.slice`
May 12 01:20:26 dcos-docker-agent1 mesos-agent[14668]: Failed to initialize systemd: Failed to locate systemd cgroups hierarchy: does not exist
May 12 01:20:26 dcos-docker-agent1 systemd[1]: dcos-mesos-slave.service: main process exited, code=exited, status=1/FAILURE
May 12 01:20:26 dcos-docker-agent1 systemd[1]: Unit dcos-mesos-slave.service entered failed state.
May 12 01:20:26 dcos-docker-agent1 systemd[1]: dcos-mesos-slave.service failed.
May 12 01:20:31 dcos-docker-agent1 systemd[1]: dcos-mesos-slave.service holdoff time over, scheduling restart.
```

**Comment by karlkfi** [comment]
Yeah, I was under the impression that systems only worked in docker if the host also had systemd. But I don't know precisely why or what the constraints are.

**Comment by adamtheturtle** [comment]
I will close this as the spec made an incorrect assumption. I will add the best documentation I can for this - given I don't completely understand it - in a follow-up which provides an alternative to using `systemd` on the host.

**Comment by adamtheturtle** [comment]
Thank you for the reviews @mhrabovcin and @karlkfi .

**Pull request closed without merging**
